os: windows
language: sh
python: "3.7"
# command to install dependencies
before_install:
  - choco install python3
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  - python -m pip install tqdm pyinstaller
# command to run tests
script:
  - pyinstaller -F vsrepo.py
